Add second task
js-tasks-ru/js-20201030_jamie pull request #2
Opened 2020-11-05 19:44 UTC by Jamie1710

functions sortStrings, pick and omit realization

2020-11-05 20:33 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-06 14:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    else if (param == 'desc') return sortArray.reverse();
было бы неплохо избавиться от `reverse` - это совершенно лишняя операция. Массив следует сортировать сразу в верном направлении

2020-11-06 14:28 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const arrFromObj = Object.entries(obj),
не экономьте на объявлении переменных. У каждой переменной должно быть свое ключевое слово `const`

2020-11-06 14:29 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-08 13:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-08 13:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-09 12:12 UTC, dosandk approved these changes

2020-11-09 12:12 UTC, merged